version: '3'

services:
  postgres:
    container_name: helpTaskDataBase
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: helpTask
    volumes:
      - ./data:/data/postgres
    ports:
      - "5432:5432"